name: Build and push Docker images CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  build:
    # Ensure test job passes before pushing image.
    needs: test
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        id: docker_build
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f
        uses: docker/build-push-action@v2.4.0
        with:
          # List of extra privileged entitlement (eg. network.host,security.insecure)
          #allow: # optional
          # List of build-time variables
          #build-args: # optional
          # Builder instance
          #builder: # optional
          # List of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)
          #cache-from: # optional
          # List of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)
          #cache-to: # optional
          # Build's context is the set of files located in the specified PATH or URL
          #context: # optional
          # Path to the Dockerfile
          #file: # optional
          # List of metadata for an image
          #labels: # optional
          # Load is a shorthand for --output=type=docker
          #load: # optional, default is false
          # Set the networking mode for the RUN instructions during build
          #network: # optional
          # Do not use cache when building the image
          #no-cache: # optional, default is false
          # List of output destinations (format: type=local,dest=path)
          #outputs: # optional
          # List of target platforms for build
          #platforms: # optional
          # Always attempt to pull a newer version of the image
          #pull: # optional, default is false
          # Push is a shorthand for --output=type=registry
          push: true # optional, default is false
          # List of secrets to expose to the build (eg. key=string, GIT_AUTH_TOKEN=mytoken)
          #secrets: # optional
          # List of secret files to expose to the build (eg. key=filename, MY_SECRET=./secret.txt)
          #secret-files: # optional
          # List of SSH agent socket or keys to expose to the build
          #ssh: # optional
          # List of tags
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudreve:latest,${{ secrets.DOCKERHUB_USERNAME }}/cloudreve:{{version}},${{ secrets.DOCKERHUB_USERNAME }}/cloudreve:{{major}}.{{minor}},${{ secrets.DOCKERHUB_USERNAME }}/cloudreve:{{major}} # optional
          # Sets the target stage to build
          #target: # optional
          # GitHub Token used to authenticate against a repository for Git context
          #github-token: # optional, default is ${{ github.token }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

